### PR TITLE
Fixes #2715095 Wrong element passed to ajax call

### PR DESCRIPTION
**Pull request by arildm**

### CODE REVIEW

**Comment by davereid** [comment]
No, the Drupal Ajax system does not want us to pass jQuery objects, it
wants the raw DOM element. Have you tested this with the latest Embed
module version?

**Comment by arildm** [comment]
Actually, I hadn't. But now I did and the bug seems to be the same. When I debug the js here, `this.element` here is not the raw DOM element, but a http://docs.ckeditor.com/#!/api/CKEDITOR.dom.element

**Comment by davereid** [comment]
Huh, we did the same fix for Entity Embed and it has been working nicely. I'm not sure why that is.

**Comment by arildm** [comment]
I just took a quick look at entity_embed now, and found these lines:

```
init: function () {
  var element = this.element;
  var $element = $(element.$);
  // Use the Ajax framework to fetch the HTML, so that we can retrieve
  // out-of-band assets (JS, CSS...).
  var entityEmbedPreview = Drupal.ajax({
    base: $element.attr('id'),
    element: $element.get(0),
```

That seems to be in line with my suggestion. `this.element` is the CKEditor DOM element; `this.element.$` is the regular DOM element, and `$element` is the jQuery object.

The only difference AFAICS is that my fix uses the expression `element.$` rather than `$element.get(0)` to access the same object. (I'm definitely fine with changing it for consistency if needed.)

**Comment by davereid** [comment]
@arildm Oh cool, I think https://github.com/drupal-media/entity_embed/pull/221 simplifies it even more in entity_embed and removes the need for using jQuery in init(). Could you incorporate these changes as well here, especially the @type JSDoc declaration?

**Comment by davereid** [comment]
Thanks so much @arildm!

**Pull request merged**
