### PR TITLE
Provide field formatters for core's URL field type

### PR DESCRIPTION
**Pull request by DevinCarlson**
Corresponding issue on Drupal.org: https://www.drupal.org/node/2546204

### CODE REVIEW

**Comment by davereid** [comment]
Sweet, I'll review this shortly!

**Comment by nalipaz** [comment]
I have tested this and it is working beautifully. Nice work!

**Comment by davereid** [comment]
I'm curious why the field vs WYSIWYG output is just slightly different?

**Comment by arildm** [comment]
@davereid, IMHO the comment for FLICKR_OUTPUT_WYSIWYG explains that pretty well.

**Comment by slashrsm** [comment]
Merged rebased branch. Commit was: d6da752 Thanks!

**Pull request closed without merging**
